[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = espidf
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0

[env:gsr-rx]
extends = env:esp32dev
build_flags =
    ${env:esp32dev.build_flags}
    -DGSR_RX_MODE
